#! /bin/sh



start() {
	echo -n "Starting snapclient: "

	# Get Rpi's serial number as unique id

	serial=$(cat /proc/cpuinfo | grep Serial | cut -d ' ' -f 2)

	start-stop-daemon -S -q -b -x snapclient -- --hostID $serial
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	echo -n "Stopping snapclient: "
	start-stop-daemon -K -q -x snapclient
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
